### PR TITLE
added unique constraint for roster global user id

### PR DESCRIPTION
**Pull request by sheebans**

### CODE REVIEW

**Comment by am-gooru** [comment]
@sheebans 

This is not needed. There is no guarantee that two different schools may have different student ids. If everyone is using incremental number they are going to overlap for sure. Not sure why this came as requirement.

**Comment by sheebans** [comment]
@am-gooru  This is the  column  you suggest to store the student code right  ? Is I'm missing something here. student code can have  the duplicate value.

**Comment by sheebans** [comment]
Do we want to create new column to store the student code ?

**Comment by am-gooru** [comment]
@sheebans Yes, this is the column to store student id. And yes, it can and will contain duplicates. The student id may be unique in a class probably or to stretch the concept, at the school level but across schools there is no guarantee. Now there may be cases like, we may want (not that I know of) to make it unique from user entered value while editing, but that would be a separate requirement.

**Pull request closed without merging**
