### PR TITLE
Updated schema changes for taxonomy

### PR DESCRIPTION
**Pull request by sheebans**

### CODE REVIEW

**Comment by am-gooru** [comment]
@sheebans Do we need to specify "NULL" at all. Not specifying not null should mean that it is nullable, right?

**Comment by sheebans** [comment]
@am-gooru  Yes! right,  if we did not specify it's consider as nullable

**Comment by am-gooru** [comment]
@sheebans 

Then should we just remove the "NULL" and pick it the default. This is what we have been doing at all places, absence of NOT NULL is nullable, and not explicit presence of NULL.

**Comment by sheebans** [comment]
@am-gooru  Removed "NULL" from schema changes

**Pull request merged**
